### ISSUE TITLE
React is a dependency of this project?

### ISSUE THREAD

**Issue by pitymaia** [cevadtokatli/window-date-picker#2]
Hello, I'm adding your window-date-picker to my project through NPM, but my partner noticed that the react and the react-dom were installed along with it in the node modules.

I was not expecting the react to be a dependency of this project, I thought it would only be necessary for your related project that implements that same datepicker for the react.

I have even deleted the react and react-dom of node_modules and the Window Date Picker continues to work perfectly.

Is this a mistake in configuring Window Date Picker dependencies?
Is it possible to add Window Date Picker to my project without having to manually delete the react?

Thank you for your attention and work.

**Comment by cevadtokatli** [comment]
Not for this version. You can check out the dependencies in [package.json](https://github.com/cevadtokatli/window-date-picker/blob/master/package.json) file. I just downloaded the window-date-picker through NPM and didn't see anything about react.

Also, If you want to use window-date-picker as React Component, you can take a look [react version](https://github.com/cevadtokatli/window-date-picker-react).

**Comment by pitymaia** [comment]
Yes, you are right. It seems that another dependency of my project introduced the react in another branch and we only realized now and we ended up thinking that it was the Windows Date Picker, because there is the react version of it.

Sorry for bothering.
