### ISSUE TITLE
The time controls seem to be reversed to me

### ISSUE THREAD

**Issue by pitymaia** [cevadtokatli/window-date-picker#3]
Hi friend, I have a real issue for you today. Not a bug, your project works wonderfully well and perfectly suits my needs. But... Humans are crazy animals.

There is a problem in human perception regarding "direction" and "ordination." This creates a UX problem for certain functions like screen scrolling, ordering items, increasing values, etc ...

For example, in Linux when I turn the mouse wheel down I go to the bottom of the page, in Mac OS this behavior is reversed. I turn down and go to the top of the page.
There is no "consensus" among humans about what is the correct behavior, due to a difference in logic that each group uses to "think" the correct one.

The same occurs with ordering items using an arrow to represent the ascending or descending order.
People do not agree on whether the up arrow should indicate ascending or descending. (There's a lot of discussion about this in stackoverflow and similar forums).

There is no right or wrong here, just different ways of facing the problem. Bootstrap 3 avoids it using other symbols to represent sort, instead of the arrows.

When I use the top controls of the Window Date Picker I hope to see the values ​​increase, because I use the logic: Up increases, down decreases.
I think you're using the mobile logic of a "wheel" where you pull the wheel down and it rotates showing a larger number.

Not a big deal, but it's a little annoying for older people who do not know that there are two logics and just think the control is "inverted". (My clients, for example).

Would it be possible, in the future, to you to add an option to change the buttons and instead of arrows change the buttons to use plus sign and minus sign?

You could use a flag in the configuration to choose between the two button types or something like this. I believe that a plus sign to increase and a minus sign to decrease does not have the ambiguity of the reported problem with arrows.

Thanks for the attention and sorry for the long description of the issue.

**Comment by cevadtokatli** [comment]
Not a problem, I'm going to add an option for this in a short time.

**Comment by nandoflorestan** [comment]
That's great news!  And thank you for the awesome component!

**Comment by cevadtokatli** [comment]
I updated the library and added two options. If you want to use arrows but reverse the orientation, you can use `orientation` option or If you want to use buttons instead of arrows then you can use `showArrowButtons` option.

**Comment by pitymaia** [comment]
That's great! Thank you very much, I'm updating my project to take advantage of this new feature.
